### Get blogs
GET http://localhost:3003/api/blogs HTTP/1.1

### Add blog
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Blog",
    "author": "Blogger",
    "url": "blogger.com",
    "likes": 10
}

### Add a user
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

  {
    "username": "Username2",
    "name": "Name2",
    "password": "p2"
  }